#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "osada"
name = "Osada"
description.en = "Decentralized publication platform and social network"
description.fr = "Plateforme de publication décentralisée et un réseau social"

version = "23.12.17~ynh1"

maintainers = ["Anmol Sharma"]

[upstream]
license = "MIT"
website = "http://zotlabs.com/osada/"
code = "https://codeberg.org/zot-archive/osada"

[integration]
yunohost = ">= 11.2"
architectures = "all"
multi_instance = true
ldap = true
sso = true
disk = "50M" # FIXME: replace with an **estimate** minimum disk requirement. e.g. 20M, 400M, 1G, ...
ram.build = "50M" # FIXME: replace with an **estimate** minimum ram requirement. e.g. 50M, 400M, 1G, ...
ram.runtime = "50M" # FIXME: replace with an **estimate** minimum ram requirement. e.g. 50M, 400M, 1G, ...

[install]
    [install.domain]
    type = "domain"

    [install.admin]
    type = "user"

[resources]
    [resources.sources]
    [resources.sources.main]
    url = "https://codeberg.org/zot-archive/osada/archive/dc8537520e0753a98bd2e2eeb1f0a16b50b954c3.tar.gz"
    sha256 = "cfed73d7d4648f4fe4e567d533d3d44dce3d36e2423c7ec32e9878f743ce2144"

    [resources.sources.app_addons]
    url = "https://codeberg.org/zot-archive/osada-addons/archive/2a39590048b3d93795918f20dc5170e9c2a4bcde.tar.gz"
    sha256 = "ba2c83145d98c2948a33eb3250bc29f3116c156f936ca56e7e3051e393804be4"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages = [
        "postgresql",
        "postgresql-contrib",

        "php7.3-mbstring",
        "php7.3-cli",
        "php7.3-imagick",
        "php7.3-xml",
        "php7.3-zip",
        "php7.3-pgsql",
        "php7.3-json",
        "php7.3-gd",
    ]

    [resources.database]
    type = "postgresql"
