#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# MANAGE SCRIPT FAILURE
#=================================================

ynh_clean_setup () {
	### Remove this function if there's nothing to clean before calling the remove script.
	true
}
# Exit if an error occurs during the execution of the script
ynh_abort_if_errors

#=================================================
# RETRIEVE ARGUMENTS FROM THE MANIFEST
#=================================================

domain=$YNH_APP_ARG_DOMAIN
path_url="/"
admin=$YNH_APP_ARG_ADMIN
email=$(ynh_user_get_info --username=$admin --key=mail)
upload="256M"
random_string="$(ynh_string_random)$(ynh_string_random)$(ynh_string_random)"
database=`expr $YNH_APP_ARG_DATABASE`

app=$YNH_APP_INSTANCE_NAME

#=================================================
# CHECK IF THE APP CAN BE INSTALLED WITH THESE ARGS
#=================================================
ynh_script_progression --message="Validating installation parameters..."

final_path=/var/www/$app
test ! -e "$final_path" || ynh_die --message="This path already contains a folder"

# Register (book) web path
ynh_webpath_register --app=$app --domain=$domain --path_url=$path_url

#=================================================
# STORE SETTINGS FROM MANIFEST
#=================================================
ynh_script_progression --message="Storing installation settings..."

ynh_app_setting_set --app=$app --key=domain   --value=$domain
ynh_app_setting_set --app=$app --key=path     --value=$path_url
ynh_app_setting_set --app=$app --key=admin    --value=$admin
ynh_app_setting_set --app=$app --key=email    --value=$email
ynh_app_setting_set --app=$app --key=upload   --value=$upload
ynh_app_setting_set --app=$app --key=database --value=$database
ynh_app_setting_set --app=$app --key=random_string --value=$random_string

#=================================================
# STANDARD MODIFICATIONS
#=================================================
# INSTALL DEPENDENCIES
#=================================================
ynh_script_progression --message="Installing dependencies..."

if [ $database -eq 2 ]; then
	ynh_install_app_dependencies $pkg_dependencies
fi

#=================================================
# CREATE DEDICATED USER
#=================================================
ynh_script_progression --message="Configuring system user..."

# Create a system user
ynh_system_user_create --username=$app --home_dir="$final_path"

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================

# 1 - Osada
ynh_script_progression --message="Setting up Osada source files..."

ynh_app_setting_set --app=$app --key=final_path --value=$final_path
# Download, check integrity, uncompress and patch the source from app.src
# ynh_setup_source --dest_dir="$final_path"
git clone https://codeberg.org/zot/osada.git "$final_path"

# 2 - Osada Addons

# Make addon Directory and unpack the Osada addons to this directory
# ynh_script_progression --message="Create addon directory inside Osada root folder..."
# mkdir $final_path/addon
ynh_script_progression --message="Setting up Osada addons source files..."

# ynh_setup_source --dest_dir="$final_path/addon" --source_id="app_addons"
pushd "$final_path"
	mkdir -p extend/addon/zaddons
	mkdir addon
	git clone  https://codeberg.org/zot/osada-addons.git $final_path/extend/addon/zaddons
	filelist=(`ls extend/addon/zaddons`)
	cd addon
	for a in "${filelist[@]}" ; do
		base=`basename $a`
		if [ $base = '.git' ]; then
			#echo 'ignoring git'
			continue;
		fi
		if [ ! -d ../extend/addon/zaddons/$base ]; then
			#echo $a 'not a directory'
			continue;
		fi
		if [ -x $base ]; then
			#echo $base 'file exists'
			continue;
		fi

		echo linking $base

		ln -s ../extend/addon/zaddons/$base $base
	done
popd


# 3 - Some extra folders
ynh_script_progression --message="Creating smarty3 folder for personal data..."

mkdir -p "${final_path}/store"
mkdir -p  "${final_path}/cache/smarty3"

# Create php.log inside Osada for logs
ynh_script_progression --message="Create php.log for the Osada debuging..."

touch "$final_path/php.log"

chmod 750 "$final_path"
chmod -R o-rwx "$final_path"
chown -R $app:www-data "$final_path"
chmod -R 755 $final_path/store $final_path/cache

#=================================================
# CREATE A  DATABASE
#=================================================

if [  $database -eq 1 ]; then
	ynh_script_progression --message="Creating a MySQL database..."
	db_name=$(ynh_sanitize_dbid --db_name=$app)
	db_user=$db_name
	ynh_app_setting_set --app=$app --key=db_name --value=$db_name
	ynh_mysql_setup_db --db_user=$db_user --db_name=$db_name
	ynh_script_progression --message="Importing database..."
	ynh_mysql_connect_as --user="$db_name" --password="$db_pwd" --database="$db_name" < $final_path/install/schema_mysql.sql
elif [ $database -eq 2 ]; then
	# Create postgresql database
	ynh_script_progression --message="Creating a postgresql database..."
	ynh_replace_string --match_string="db_type = 0;" --replace_string="db_type = 1;" --target_file="$config"
	db_name=$(ynh_sanitize_dbid --db_name=$app)
	db_user=$app
	ynh_psql_test_if_first_run
	ynh_psql_setup_db --db_user=$db_user --db_name=$db_name
	ynh_app_setting_set --app=$app --key=db_name --value=$db_name
	ynh_script_progression --message="Importing database..."
	ynh_psql_connect_as --user="$db_name" --password="$db_pwd" --database="$db_name" < $final_path/install/schema_postgres.sql
else
	ynh_die --message="Some problem occured in creating the database, contact maintainer"
fi

#=================================================
# PHP-FPM CONFIGURATION
#=================================================
ynh_script_progression --message="Configuring PHP-FPM..."

# Create a dedicated PHP-FPM config
ynh_add_fpm_config --package="$extra_php_dependencies"
phpversion=$(ynh_app_setting_get --app=$app --key=phpversion)

#=================================================
# MODIFY A CONFIG FILE
#=================================================

ynh_add_config --template="../conf/htconfig.sample.php" --destination="$final_path/.htconfig.php"

# addon ldap config
ynh_add_config --template="../conf/ldap_conf.php" --destination="$final_path/.htconfig.php"

#=================================================
# NGINX CONFIGURATION
#=================================================
ynh_script_progression --message="Configuring NGINX web server..."

# Create a dedicated NGINX config
ynh_add_nginx_config

#=================================================
# SETUP CRON JOB
#=================================================
ynh_script_progression --message="Setting up cron job..."

ynh_add_config --template="../conf/cron" --destination="/etc/cron.d/$app"

#=================================================
# STORE THE CONFIG FILE CHECKSUM
#=================================================

# Calculate and store the config file checksum into the app settings
ynh_store_file_checksum --file="$config"

#=================================================
# SETUP LOGROTATE
#=================================================
ynh_script_progression --message="Configuring log rotation..."

# Use logrotate to manage application logfile(s)
ynh_use_logrotate "$final_path/php.log"

#=================================================
# SETUP FAIL2BAN
#=================================================
ynh_script_progression --message="Add Fail2Ban..."

ynh_add_fail2ban_config --logpath="$final_path/php.log" --failregex="^.*auth\.php.*failed login attempt.*from IP <HOST>.*$" --max_retry="5"

#=================================================
# SETUP SSOWAT
#=================================================
ynh_script_progression --message="Configuring permissions..."

# As Osada is social network and have its own permission there is no need to keep Osada behind SSO
ynh_permission_update --permission="main" --add="visitors"

#=================================================
# RELOAD NGINX
#=================================================
ynh_script_progression --message="Reloading NGINX web server..."

ynh_systemd_action --service_name=nginx --action=reload

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression --message="Installation of $app completed"
